# Generated by Django 5.0.1 on 2024-01-04 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='StatusRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.IntegerField()),
                ('cns', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('emissao_rg', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('nome_mae', models.CharField(max_length=255)),
                ('nome_pai', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('operador', models.IntegerField(blank=True, default=None, null=True)),
                ('profissional', models.IntegerField(blank=True, default=None, null=True)),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinculos.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('data_edicao', models.DateField(auto_now=True)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinculos.funcao')),
                ('funcionario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vinculos.funcionario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinculos.local')),
                ('status_cnes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='status_cnes', to='vinculos.status')),
                ('status_ids', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='status_ids', to='vinculos.status')),
                ('status_rh', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vinculos.statusrh')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinculos.tipo')),
            ],
        ),
    ]
