# Generated by Django 5.0.1 on 2024-01-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='descricao',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='status',
            name='descricao',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='statusrh',
            name='descricao',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='descricao',
            field=models.CharField(max_length=31),
        ),
    ]
