# Generated by Django 5.0.1 on 2024-01-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0002_alter_funcao_descricao_alter_local_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=63)),
            ],
        ),
        migrations.AddField(
            model_name='vinculo',
            name='tipo_vinculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vinculos.tipovinculo'),
        ),
    ]
