# Generated by Django 5.0.1 on 2024-01-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0005_alter_funcionario_cns_alter_funcionario_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
