# Generated by Django 5.0.1 on 2024-01-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0006_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='crm',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
